### ISSUE TITLE
插件挂了？

### ISSUE THREAD

**Issue by v8wzge** [web1n/feed-wocampus#1]
学长，插件可能挂了？稳定使用了不到一天就掉线了，并且无法再次连接，重新编译固件依然不可用

**Comment by web1n** [comment]
哪个学校？联通校园认证网关的心跳包认证是坏的，所以每24h会掉线。有写掉线自动重播，你可以看一下系统日志有没有相关日志

**Comment by v8wzge** [comment]
河北科大

**Comment by web1n** [comment]
我这儿没问题。你可以再试着拨一下，到第二天无法上网时候看看是否有相关日志

**Comment by v8wzge** [comment]
谢谢学长了

**Comment by v8wzge** [comment]
Fri May 21 20:54:06 2021 daemon.warn miniupnpd[14090]: SSDP packet sender 192.168.255.1:1900 not from a LAN, ignoring
Fri May 21 20:54:06 2021 daemon.warn miniupnpd[14090]: SSDP packet sender 192.168.255.1:1900 not from a LAN, ignoring
Fri May 21 20:54:06 2021 daemon.warn miniupnpd[14090]: SSDP packet sender 192.168.255.1:1900 not from a LAN, ignoring
Fri May 21 20:54:06 2021 daemon.warn miniupnpd[14090]: SSDP packet sender 192.168.255.1:1900 not from a LAN, ignoring
Fri May 21 20:54:06 2021 daemon.warn miniupnpd[14090]: SSDP packet sender 192.168.255.1:1900 not from a LAN, ignoring
Fri May 21 20:54:06 2021 daemon.warn miniupnpd[14090]: SSDP packet sender 192.168.255.1:1900 not from a LAN, ignoring
Fri May 21 20:54:06 2021 daemon.warn miniupnpd[14090]: SSDP packet sender 192.168.255.1:1900 not from a LAN, ignoring
系统日志全是这个

**Comment by web1n** [comment]
那是upnp的日志，和本插件没有关系

**Comment by v8wzge** [comment]
是不是有冲突

**Comment by v8wzge** [comment]
重启后也全是这个

**Comment by web1n** [comment]
> 那是upnp的日志，和本插件没有关系

**Comment by v8wzge** [comment]
Fri May 21 21:01:46 2021 daemon.notice netifd: Interface 'wan' is now down
Fri May 21 21:01:46 2021 daemon.notice netifd: Interface 'wan' has link connectivity loss
Fri May 21 21:01:46 2021 daemon.notice netifd: Interface 'wan' is setting up now
Fri May 21 21:01:46 2021 daemon.notice netifd: Interface 'wan' has link connectivity
Fri May 21 21:01:46 2021 daemon.info avahi-daemon[4889]: Withdrawing address record for 10.255.143.105 on eth0.
Fri May 21 21:01:46 2021 daemon.info avahi-daemon[4889]: Leaving mDNS multicast group on interface eth0.IPv4 with address 10.255.143.105.
Fri May 21 21:01:46 2021 daemon.info avahi-daemon[4889]: Interface eth0.IPv4 no longer relevant for mDNS.
Fri May 21 21:01:46 2021 daemon.notice netifd: wan (4369): udhcpc: started, v1.31.1
Fri May 21 21:01:46 2021 daemon.notice netifd: wan (4369): udhcpc: sending discover
Fri May 21 21:01:46 2021 daemon.notice netifd: wan (4369): udhcpc: sending select for 10.255.143.105
Fri May 21 21:01:46 2021 daemon.notice netifd: wan (4369): udhcpc: lease of 10.255.143.105 obtained, lease time 259200
Fri May 21 21:01:46 2021 daemon.info avahi-daemon[4889]: Joining mDNS multicast group on interface eth0.IPv4 with address 10.255.143.105.
Fri May 21 21:01:46 2021 daemon.info avahi-daemon[4889]: New relevant interface eth0.IPv4 for mDNS.
Fri May 21 21:01:46 2021 daemon.info avahi-daemon[4889]: Registering new address record for 10.255.143.105 on eth0.IPv4.
Fri May 21 21:01:46 2021 daemon.notice netifd: Interface 'wan' is now up
Fri May 21 21:01:50 2021 user.notice wan: /usr/lib/wocampus/campus.sh: line 15: php-cli: not found
Fri May 21 21:01:58 2021 user.notice firewall: Reloading firewall due to ifup of wan (eth0)
依赖丢了，这是怎么回事，好好的php-cli没了
